"""
app.py  ─  Interactive Sales Dashboard
=======================================
Framework : Streamlit
Charts    : Plotly Express / Graph Objects
Data      : ventas_demo.csv  (generated by generate_data.py)

Run:
    $ streamlit run app.py
"""

# ── Imports ───────────────────────────────────────────────────────────────────
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from datetime import date

# ══════════════════════════════════════════════════════════════════════════════
# 0. GLOBAL PAGE CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="Sales Dashboard · MVP",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Corporate color palette ───────────────────────────────────────────────────
PRIMARY   = "#4F8EF7"
SECONDARY = "#34D399"
DANGER    = "#F87171"
SURFACE   = "#1E293B"
TEXT      = "#F1F5F9"

PLOTLY_TEMPLATE = "plotly_dark"
COLOR_SEQ = px.colors.qualitative.Bold

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown(
    """
    <style>
        /* General background */
        [data-testid="stAppViewContainer"] { background: #0F172A; }
        [data-testid="stSidebar"]          { background: #1E293B; }

        /* KPI cards */
        .kpi-card {
            background: #1E293B;
            border-radius: 12px;
            padding: 22px 28px;
            text-align: center;
            border-left: 4px solid #4F8EF7;
            box-shadow: 0 4px 20px rgba(0,0,0,.35);
        }
        .kpi-label { color: #94A3B8; font-size: 13px; text-transform: uppercase;
                     letter-spacing: .08em; margin-bottom: 6px; }
        .kpi-value { color: #F1F5F9; font-size: 32px; font-weight: 700; }
        .kpi-delta { font-size: 13px; margin-top: 4px; }
        .up   { color: #34D399; }
        .down { color: #F87171; }

        /* Dashboard header */
        .dash-header { padding: 10px 0 20px 0; border-bottom: 1px solid #334155;
                       margin-bottom: 24px; }

        /* Tables */
        [data-testid="stDataFrame"] { border-radius: 10px; overflow: hidden; }
    </style>
    """,
    unsafe_allow_html=True,
)


# ══════════════════════════════════════════════════════════════════════════════
# 1. DATA LOADING & CACHE
# ══════════════════════════════════════════════════════════════════════════════
DATA_FILE = Path("ventas_demo.csv")


@st.cache_data(show_spinner="Loading data…")
def load_data(path: Path) -> pd.DataFrame:
    """Read CSV, validate columns and apply correct types."""
    required_cols = {"Fecha", "Producto", "Región", "Ventas_USD", "Unidades", "Costo_USD"}
    df = pd.read_csv(path, parse_dates=["Fecha"])
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in CSV: {missing}")
    df["Ganancia_USD"] = df["Ventas_USD"] - df["Costo_USD"]
    df["Mes"]          = df["Fecha"].dt.to_period("M").dt.to_timestamp()
    return df


# ── Load data ─────────────────────────────────────────────────────────────────
if not DATA_FILE.exists():
    st.error(
        "⚠️  **ventas_demo.csv** not found. "
        "Please run `python generate_data.py` first to generate the demo data."
    )
    st.stop()

try:
    df_raw = load_data(DATA_FILE)
except Exception as exc:
    st.error(f"Error reading data file: {exc}")
    st.stop()


# ══════════════════════════════════════════════════════════════════════════════
# 2. SIDEBAR  ─  Interactive filters
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.image(
        "https://img.icons8.com/color/96/combo-chart.png",
        width=64,
    )
    st.title("Sales Dashboard")
    st.caption("MVP · v1.0")
    st.divider()

    # ── Filter: Date range ────────────────────────────────────────────────────
    st.subheader("📅 Date Range")
    min_date = df_raw["Fecha"].min().date()
    max_date = df_raw["Fecha"].max().date()

    date_start, date_end = st.date_input(
        "Select period",
        value=(min_date, max_date),
        min_value=min_date,
        max_value=max_date,
        format="DD/MM/YYYY",
    )

    st.divider()

    # ── Filter: Region ────────────────────────────────────────────────────────
    st.subheader("🌎 Region")
    all_regions  = sorted(df_raw["Región"].unique())
    sel_regions  = st.multiselect(
        "Select regions",
        options=all_regions,
        default=all_regions,
        placeholder="Choose one or more…",
    )

    st.divider()

    # ── Filter: Product ───────────────────────────────────────────────────────
    st.subheader("📦 Product")
    all_products = sorted(df_raw["Producto"].unique())
    sel_products = st.multiselect(
        "Select products",
        options=all_products,
        default=all_products,
        placeholder="Choose one or more…",
    )

    st.divider()
    st.caption("Demo data · 2024")


# ══════════════════════════════════════════════════════════════════════════════
# 3. APPLY FILTERS
# ══════════════════════════════════════════════════════════════════════════════
# Handle the case where date_input returns a single value (incomplete range)
if isinstance(date_start, date) and isinstance(date_end, date):
    pass
else:
    date_start = min_date
    date_end   = max_date

df = df_raw[
    (df_raw["Fecha"].dt.date >= date_start) &
    (df_raw["Fecha"].dt.date <= date_end)   &
    (df_raw["Región"].isin(sel_regions  if sel_regions  else all_regions))  &
    (df_raw["Producto"].isin(sel_products if sel_products else all_products))
].copy()


# ══════════════════════════════════════════════════════════════════════════════
# 4. VALIDATION: Empty DataFrame
# ══════════════════════════════════════════════════════════════════════════════
if df.empty:
    st.warning(
        "⚠️  No results found for the selected filters. "
        "Try adjusting the date range or the region / product filters."
    )
    st.stop()


# ══════════════════════════════════════════════════════════════════════════════
# 5. DASHBOARD HEADER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown(
    f"""
    <div class="dash-header">
        <h1 style="color:{TEXT}; margin:0; font-size:28px;">
            📊 Sales Dashboard · 2024
        </h1>
        <p style="color:#94A3B8; margin:4px 0 0 0; font-size:14px;">
            Period: {date_start.strftime('%d %b %Y')} → {date_end.strftime('%d %b %Y')}
            &nbsp;·&nbsp; {len(df):,} orders shown
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)


# ══════════════════════════════════════════════════════════════════════════════
# 6. MAIN KPIs
# ══════════════════════════════════════════════════════════════════════════════
total_ventas   = df["Ventas_USD"].sum()
total_ganancia = df["Ganancia_USD"].sum()
total_pedidos  = len(df)
margen_pct     = (total_ganancia / total_ventas * 100) if total_ventas else 0
total_unidades = df["Unidades"].sum()

# Share vs. full period to compute delta
pct_del_total  = (total_ventas / df_raw["Ventas_USD"].sum() * 100)

kpi1, kpi2, kpi3, kpi4 = st.columns(4)

def render_kpi(col, label: str, value: str, delta: str, up: bool):
    direction = "up" if up else "down"
    arrow     = "▲" if up else "▼"
    col.markdown(
        f"""
        <div class="kpi-card">
            <div class="kpi-label">{label}</div>
            <div class="kpi-value">{value}</div>
            <div class="kpi-delta {direction}">{arrow} {delta}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

with kpi1:
    render_kpi(
        kpi1,
        "💰 Total Revenue",
        f"${total_ventas:,.0f}",
        f"{pct_del_total:.1f}% of full year",
        up=True,
    )
with kpi2:
    render_kpi(
        kpi2,
        "📈 Net Profit",
        f"${total_ganancia:,.0f}",
        f"Margin {margen_pct:.1f}%",
        up=margen_pct >= 30,
    )
with kpi3:
    render_kpi(
        kpi3,
        "🛒 Total Orders",
        f"{total_pedidos:,}",
        f"Avg. ticket ${total_ventas/total_pedidos:,.0f}",
        up=True,
    )
with kpi4:
    render_kpi(
        kpi4,
        "📦 Units Sold",
        f"{total_unidades:,}",
        f"Avg. {total_unidades/total_pedidos:.1f} u/order",
        up=True,
    )

st.markdown("<br>", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# 7. CHARTS  ─  Row 1: Bar by Product  +  Donut by Region
# ══════════════════════════════════════════════════════════════════════════════
col_bar, col_pie = st.columns([3, 2], gap="large")

# ── 7a. Bar chart: Revenue by Product ────────────────────────────────────────
with col_bar:
    st.subheader("🏆 Revenue by Product")

    df_prod = (
        df.groupby("Producto", as_index=False)
          .agg(Ventas=("Ventas_USD", "sum"), Ganancia=("Ganancia_USD", "sum"))
          .sort_values("Ventas", ascending=True)
    )

    fig_bar = go.Figure()
    fig_bar.add_trace(go.Bar(
        y=df_prod["Producto"],
        x=df_prod["Ventas"],
        name="Revenue",
        orientation="h",
        marker_color=PRIMARY,
        text=df_prod["Ventas"].apply(lambda v: f"${v:,.0f}"),
        textposition="outside",
    ))
    fig_bar.add_trace(go.Bar(
        y=df_prod["Producto"],
        x=df_prod["Ganancia"],
        name="Profit",
        orientation="h",
        marker_color=SECONDARY,
        text=df_prod["Ganancia"].apply(lambda v: f"${v:,.0f}"),
        textposition="outside",
        visible="legendonly",
    ))
    fig_bar.update_layout(
        template=PLOTLY_TEMPLATE,
        barmode="overlay",
        height=340,
        margin=dict(l=0, r=60, t=10, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        xaxis_title="USD",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=TEXT),
    )
    st.plotly_chart(fig_bar, use_container_width=True)

# ── 7b. Donut: Distribution by Region ────────────────────────────────────────
with col_pie:
    st.subheader("🌎 Share by Region")

    df_reg = (
        df.groupby("Región", as_index=False)["Ventas_USD"]
          .sum()
          .sort_values("Ventas_USD", ascending=False)
    )

    fig_pie = px.pie(
        df_reg,
        names="Región",
        values="Ventas_USD",
        hole=0.52,
        color_discrete_sequence=COLOR_SEQ,
        template=PLOTLY_TEMPLATE,
    )
    fig_pie.update_traces(
        textposition="outside",
        textinfo="label+percent",
    )
    fig_pie.update_layout(
        height=340,
        margin=dict(l=10, r=10, t=10, b=10),
        showlegend=False,
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(color=TEXT),
    )
    st.plotly_chart(fig_pie, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# 8. CHART  ─  Row 2: Monthly sales trend
# ══════════════════════════════════════════════════════════════════════════════
st.subheader("📆 Monthly Sales Trend")

df_monthly = (
    df.groupby(["Mes", "Producto"], as_index=False)["Ventas_USD"]
      .sum()
)

fig_line = px.line(
    df_monthly,
    x="Mes",
    y="Ventas_USD",
    color="Producto",
    markers=True,
    labels={"Ventas_USD": "Revenue (USD)", "Mes": "Month", "Producto": "Product"},
    template=PLOTLY_TEMPLATE,
    color_discrete_sequence=COLOR_SEQ,
)
fig_line.update_traces(line_width=2.5, marker_size=7)
fig_line.update_layout(
    height=380,
    margin=dict(l=0, r=0, t=10, b=10),
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    xaxis_title="",
    yaxis_title="Revenue (USD)",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(color=TEXT),
    xaxis=dict(gridcolor="#1E293B"),
    yaxis=dict(gridcolor="#334155"),
)
st.plotly_chart(fig_line, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# 9. HEATMAP  ─  Revenue by Region × Month
# ══════════════════════════════════════════════════════════════════════════════
st.subheader("🗺️ Heat Map: Revenue by Region and Month")

df_heat = (
    df.groupby(["Mes", "Región"])["Ventas_USD"]
      .sum()
      .reset_index()
      .pivot(index="Región", columns="Mes", values="Ventas_USD")
      .fillna(0)
)
df_heat.columns = [c.strftime("%b %Y") for c in df_heat.columns]

fig_heat = px.imshow(
    df_heat,
    color_continuous_scale="Blues",
    aspect="auto",
    template=PLOTLY_TEMPLATE,
    labels=dict(color="Revenue (USD)"),
)
fig_heat.update_layout(
    height=280,
    margin=dict(l=0, r=0, t=10, b=10),
    paper_bgcolor="rgba(0,0,0,0)",
    font=dict(color=TEXT),
    coloraxis_colorbar=dict(title="USD"),
)
st.plotly_chart(fig_heat, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# 10. INTERACTIVE TABLE + CSV DOWNLOAD
# ══════════════════════════════════════════════════════════════════════════════
st.subheader("📋 Filtered Order Details")

# Format monetary columns for display
df_display = df[[
    "Fecha", "Producto", "Región", "Unidades", "Ventas_USD", "Costo_USD", "Ganancia_USD"
]].copy()
df_display["Fecha"] = df_display["Fecha"].dt.strftime("%d/%m/%Y")

# Show table with fixed height and scroll
st.dataframe(
    df_display.sort_values("Ventas_USD", ascending=False).reset_index(drop=True),
    use_container_width=True,
    height=320,
    column_config={
        "Ventas_USD":   st.column_config.NumberColumn("Revenue (USD)", format="$%.2f"),
        "Costo_USD":    st.column_config.NumberColumn("Cost (USD)",    format="$%.2f"),
        "Ganancia_USD": st.column_config.NumberColumn("Profit (USD)",  format="$%.2f"),
        "Unidades":     st.column_config.NumberColumn("Units",         format="%d"),
    },
)

# ── Download button ───────────────────────────────────────────────────────────
csv_bytes = df_display.to_csv(index=False, sep=";", decimal=",").encode("utf-8-sig")

col_dl, col_info = st.columns([1, 4])
with col_dl:
    st.download_button(
        label="⬇️  Download filtered CSV",
        data=csv_bytes,
        file_name=f"sales_{date_start}_{date_end}.csv",
        mime="text/csv",
        use_container_width=True,
    )
with col_info:
    st.caption(
        f"📄  {len(df_display):,} rows  ·  "
        f"Period: {date_start.strftime('%d/%m/%Y')} → {date_end.strftime('%d/%m/%Y')}"
    )


# ══════════════════════════════════════════════════════════════════════════════
# 11. FOOTER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown(
    """
    <div style="text-align:center; color:#475569; font-size:12px; border-top:1px solid #1E293B; padding-top:16px;">
        Sales Dashboard MVP · Built with Streamlit &amp; Plotly
        &nbsp;·&nbsp; Synthetically generated demo data
    </div>
    """,
    unsafe_allow_html=True,
)